import { Skill } from './skill';

export const Skills: Skill[] = [
  { tag:"JavaScript", weight:undefined},
  { tag:"HTML/CSS", weight:undefined},
  { tag:"SQL", weight:undefined},
  { tag:"Python", weight:undefined},
  { tag:"Java", weight:undefined},
  { tag:"Bash/Shell/PowerShell", weight:undefined},
  { tag:"C#", weight:undefined},
  { tag:"PHP", weight:undefined},
  { tag:"C++", weight:undefined},
  { tag:"TypeScript", weight:undefined},
  { tag:"C", weight:undefined},
  { tag:"Ruby", weight:undefined},
  { tag:"Go", weight:undefined},
  { tag:"Assembly", weight:undefined},
  { tag:"Swift", weight:undefined},
  { tag:"Kotlin", weight:undefined},
  { tag:"Objective-C", weight:undefined},
  { tag:"Scala", weight:undefined},
  { tag:"Rust", weight:undefined},
  { tag:"Dart", weight:undefined},
  { tag:"WebAssembly", weight:undefined},
  { tag:"jQuery", weight:undefined},
  { tag:"React.js", weight:undefined},
  { tag:"Angular/Angular.js", weight:undefined},
  { tag:"ASP.NET", weight:undefined},
  { tag:"Spring", weight:undefined},
  { tag:"Express", weight:undefined},
  { tag:"Vue.js", weight:undefined},
  { tag:"Django", weight:undefined},
  { tag:"Laravel", weight:undefined},
  { tag:"Ruby on Rails", weight:undefined},
  { tag:"Drupal", weight:undefined},
  { tag:"WordPress", weight:undefined},
  { tag:"Node.js", weight:undefined},
  { tag:".NET", weight:undefined},
  { tag:".NET Core", weight:undefined},
  { tag:"Unity 3D", weight:undefined},
  { tag:"TensorFlow", weight:undefined},
  { tag:"React Native", weight:undefined},
  { tag:"Cordova", weight:undefined},
  { tag:"Xamarin", weight:undefined},
  { tag:"Hadoop", weight:undefined},
  { tag:"Apache Spark", weight:undefined},
  { tag:"Docker", weight:undefined},
  { tag:"Flutter", weight:undefined},
  { tag:"MySQL", weight:undefined},
  { tag:"PostgreSQL", weight:undefined},
  { tag:"Microsoft SQL Server", weight:undefined},
  { tag:"SQLite", weight:undefined},
  { tag:"MongoDB", weight:undefined},
  { tag:"Redis", weight:undefined},
  { tag:"MariaDB", weight:undefined},
  { tag:"Oracle", weight:undefined},
  { tag:"Elasticsearch", weight:undefined},
  { tag:"Firebase", weight:undefined},
  { tag:"DynamoDB", weight:undefined},
  { tag:"AWS", weight:undefined},
  { tag:"Microsoft Azure", weight:undefined},
  { tag:"Google Cloud Platform", weight:undefined},
  { tag:"TypeScript", weight:undefined},
  { tag:"Kotlin", weight:undefined},
  { tag:"Swift", weight:undefined},
  { tag:"F#", weight:undefined}  
];
